# Generated by Django 2.1.2 on 2018-11-01 08:21

import chimera_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20, unique=True, verbose_name='user name')),
                ('email', models.EmailField(max_length=20, verbose_name='email address')),
                ('password', models.CharField(max_length=500, verbose_name='hashed password')),
                ('salt', models.CharField(max_length=100, verbose_name='salt')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', chimera_core.models.UserManager()),
            ],
        ),
    ]
