# Generated by Django 2.1.2 on 2019-01-22 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chimera_core', '0002_auto_20181121_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chimera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chimera_code', models.CharField(max_length=100)),
                ('tempname_list', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
