# Generated by Django 2.1.2 on 2019-01-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimera_core', '0003_chimera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chimera',
            name='user',
        ),
        migrations.AddField(
            model_name='chimera',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
    ]
