# Generated by Django 2.1.2 on 2019-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimera_core', '0004_auto_20190122_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chimera',
            name='chimera_code',
            field=models.TextField(),
        ),
    ]
