# Generated by Django 2.1.2 on 2019-02-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chimera_core', '0005_auto_20190122_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_dur',
            field=models.FloatField(default=0.0),
        ),
    ]
