# Generated by Django 2.1.2 on 2019-04-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chimera_core', '0006_user_login_dur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_dur',
        ),
    ]
